# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventaboutus',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
        migrations.AlterField(
            model_name='eventawards',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
        migrations.AlterField(
            model_name='eventcontactus',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
        migrations.AlterField(
            model_name='eventrunreport',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
        migrations.AlterField(
            model_name='eventsuccessstoreis',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
        migrations.AlterField(
            model_name='eventthankmsg',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
    ]
