# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0003_auto_20190122_0655'),
        ('Events', '0002_auto_20190122_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_categories',
            field=models.ManyToManyField(related_name='Allowed_categories', to='NGO.FundraiserType'),
        ),
        migrations.AddField(
            model_name='event',
            name='display',
            field=models.ManyToManyField(related_name='fundraisertype_related_to_event', to='NGO.FundraiserType'),
        ),
        migrations.AddField(
            model_name='event',
            name='display_one',
            field=models.ManyToManyField(related_name='fundraisertype_related_to_event_for_frontend_scroller', to='NGO.FundraiserType'),
        ),
        migrations.AddField(
            model_name='event',
            name='fundraisers',
            field=models.ManyToManyField(to='NGO.Fundraiser'),
        ),
        migrations.AddField(
            model_name='event',
            name='ngo',
            field=models.ManyToManyField(to='NGO.NGO'),
        ),
        migrations.AddField(
            model_name='eventngodescription',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
    ]
