# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20190122_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributinghotels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'static/%Y/%m/%d', verbose_name=b'Icon'),
        ),
        migrations.AlterField(
            model_name='corporatetables',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'static/%Y/%m/%d', verbose_name=b'Icon'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_page_widget',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='join_us_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_page_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='small_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='widget',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='widget_icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='wishtree_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventarticle',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text=b'Image size should be 930x300 pixels', null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='home_page_widget',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='join_us_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='main_page_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='small_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='widget',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='widget_icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='wishtree_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventbanners',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text=b'Image size should be 930x300 pixels', null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventthankmsg',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
    ]
