# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-17 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20190205_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allowed_categories',
            field=models.ManyToManyField(related_name='_event_allowed_categories_+', to='NGO.FundraiserType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Event End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name=b'Event Contact Email ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(verbose_name=b'Event URL/Slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Event Start Date'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Event End Date'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='event_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name=b'Event Contact Email ID'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Event Name'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='slug',
            field=models.SlugField(verbose_name=b'Event URL/Slug'),
        ),
        migrations.AlterField(
            model_name='eventauditlogentry',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Event Start Date'),
        ),
    ]
