# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-29 06:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_auto_20190617_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(verbose_name=b'Campaign URL/Slug')),
                ('widget_icon', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name=b'Campaign start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=b'Campaign end date')),
                ('campaign_logo', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d')),
                ('youtube_embedded', models.URLField(blank=True, help_text=b'For example : https://www.youtube.com/embed/23WbluYCUe8', null=True, verbose_name=b'Youtube Embedded Link')),
                ('campaign_email', models.EmailField(max_length=100, verbose_name=b'Contact Email ID')),
                ('mission', models.TextField(null=True, verbose_name=b'Mission')),
                ('our_work', models.TextField(null=True, verbose_name=b'Our Work')),
                ('support_for_cause', models.TextField(null=True, verbose_name=b'Support for the cause')),
                ('our_mission', models.TextField(max_length=250, null=True, verbose_name=b'Our Mission')),
                ('target_amt', models.IntegerField(blank=True, max_length=100, null=True, verbose_name=b'Targetted amount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
