# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-02-07 11:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_auto_20191111_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('gallery', models.BooleanField(default=True)),
                ('event_type', models.BooleanField(default=True)),
                ('fundraisers', models.BooleanField(default=True)),
                ('corporates', models.BooleanField(default=True)),
                ('csos', models.BooleanField(default=True)),
                ('last_year_highlights', models.BooleanField(default=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('our_work', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('support_for_the_cause', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
