# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-12-22 06:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_eventconfig_eventextended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventngodescription',
            name='work_acheivement',
            field=ckeditor.fields.RichTextField(blank=True, help_text=b'Should not exceed 2000 characters', null=True, verbose_name=b'Our Work'),
        ),
    ]
