# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-02-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_auto_20210108_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventamountdeduction',
            name='percent',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
