# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-03-29 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_auto_20210212_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='campaign_type',
            field=models.CharField(blank=True, choices=[('GC', 'Genral Campaign'), ('CFC', 'Campaign with CSO and Fundraiser'), ('FC', 'Campaign with isupport fundraisers')], max_length=400, null=True, verbose_name=b'Campaign Type'),
        ),
        migrations.AddField(
            model_name='eventauditlogentry',
            name='campaign_type',
            field=models.CharField(blank=True, choices=[('GC', 'Genral Campaign'), ('CFC', 'Campaign with CSO and Fundraiser'), ('FC', 'Campaign with isupport fundraisers')], max_length=400, null=True, verbose_name=b'Campaign Type'),
        ),
    ]
