# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-04-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_auto_20210329_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feature_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventauditlogentry',
            name='feature_event',
            field=models.BooleanField(default=False),
        ),
    ]
