# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-04-20 05:44
from __future__ import unicode_literals

from django.db import migrations
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_auto_20210419_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/banner/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='eventauditlogentry',
            name='banner_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/banner/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventthankmsg',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
    ]
