# Generated by Django 3.2 on 2021-07-15 17:43

import ckeditor.fields
import csr.views
from django.db import migrations, models
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_auto_20210420_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allowedcategory',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_email',
            field=models.EmailField(max_length=100, verbose_name='Contact Email ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Campaign end date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='mission',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='our_mission',
            field=models.TextField(max_length=250, null=True, verbose_name='Our Mission'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='our_work',
            field=models.TextField(null=True, verbose_name='Our Work'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(verbose_name='Campaign URL/Slug'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Campaign start date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='support_for_cause',
            field=models.TextField(null=True, verbose_name='Support for the cause'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_amt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Targetted amount'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='widget_icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='youtube_embedded',
            field=models.URLField(blank=True, help_text='For example : https://www.youtube.com/embed/23WbluYCUe8', null=True, verbose_name='Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='contributinghotels',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contributinghotels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='contributinghotels',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
        migrations.AlterField(
            model_name='corporatetables',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='corporatetables',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='corporatetables',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/banner/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Add a Banner header'),
        ),
        migrations.AlterField(
            model_name='event',
            name='campaign_type',
            field=models.CharField(blank=True, choices=[('GC', 'Genral Campaign'), ('CFC', 'Campaign with CSO and Fundraiser'), ('FC', 'Campaign with isupport fundraisers')], max_length=400, null=True, verbose_name='Campaign Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_one_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Event Contact Email ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Marathon', 'Marathon'), ('Daan Utsav', 'Daan Utsav'), ('Cyclothon', 'Cyclothon'), ('Campaign', 'Campaign'), ('Others', 'Others')], max_length=400, null=True, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fundraiser_donation_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fundraiser Donation Amount'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_page_widget',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='join_us_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_page_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_page_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Page Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(verbose_name='Event URL/Slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='small_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Target amount'),
        ),
        migrations.AlterField(
            model_name='event',
            name='widget',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='widget_icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='wishtree_logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='eventaboutus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventamountdeduction',
            name='etype',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Wishtree', 'Wishtree')], default='Other', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventamountdeduction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventamountdeduction',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='eventarticle',
            name='display',
            field=models.CharField(blank=True, choices=[('1', 'Home Page')], max_length=400, null=True, verbose_name='Display'),
        ),
        migrations.AlterField(
            model_name='eventarticle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventarticle',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text='Image size should be 930x300 pixels', null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='eventarticle',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
        migrations.AlterField(
            model_name='eventarticle',
            name='summary',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Byline/ Summary'),
        ),
        migrations.AlterField(
            model_name='eventawards',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventawards',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='eventbanners',
            name='URL',
            field=models.URLField(blank=True, verbose_name='Link url'),
        ),
        migrations.AlterField(
            model_name='eventbanners',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='eventbanners',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventbanners',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventbanners',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text='Image size should be 930x300 pixels', null=True, upload_to='static/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventcontactus',
            name='email1',
            field=models.EmailField(max_length=60, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='eventcontactus',
            name='email2',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='eventcontactus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventextended',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='address1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address1'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='address2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address2'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='black_board_message',
            field=models.TextField(blank=True, null=True, verbose_name='Black board messages'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='fund_utilisation_statement',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Fund Utilisation statement'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='our_mission',
            field=models.TextField(blank=True, null=True, verbose_name='Mission Statement'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone1'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='web_address',
            field=models.URLField(blank=True, null=True, verbose_name='Web Address'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='work_acheivement',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Should not exceed 2000 characters', null=True, verbose_name='Our Work'),
        ),
        migrations.AlterField(
            model_name='eventngodescription',
            name='youtube_embedd',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='eventrunreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventrunreport',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='eventsuccessstoreis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventsuccessstoreis',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='eventthankmsg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventthankmsg',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.DeleteModel(
            name='EventAuditLogEntry',
        ),
    ]
