# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-21 14:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mcms.thumbs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title of the Project:')),
                ('icon', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/images/%Y/%m/%d')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('problem', ckeditor.fields.RichTextField(blank=True, help_text=b'maximum 200 characters', null=True, verbose_name=b'The problem:')),
                ('how_project_will_solve_problem', ckeditor.fields.RichTextField(blank=True, help_text=b'maximum 200 characters', null=True, verbose_name=b'How will this project solve the problem?:')),
                ('long_term_impact', ckeditor.fields.RichTextField(blank=True, help_text=b'maximum 200 characters', null=True, verbose_name=b'What is the long term impact of this project?:')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name=b'Start date')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Goal')),
                ('project_status', models.IntegerField(choices=[(0, b'Pending'), (1, b'Started'), (2, b'In Progress'), (3, b'Completed')], verbose_name=b'Project Status')),
                ('upload_pdf', models.FileField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('for_donate_mail', models.BooleanField(default=False)),
                ('for_fundraise_page', models.BooleanField(default=False)),
                ('for_every_month_report', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('people_supported', models.CharField(blank=True, max_length=10, null=True)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.Cause')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
            ],
            options={
                'db_table': 'Projects_project_cause',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Projects_social_network',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='we_are_on',
            field=models.ManyToManyField(to='Projects.SocialNetwork'),
        ),
    ]
