# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-21 14:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mcms.thumbs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('url', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Mobile')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'City')),
                ('pincode', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Pincode')),
                ('documnt', models.FileField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcms.Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcms.State')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
