# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms', '0002_auto_20190122_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
    ]
