# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms', '0003_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='filetype',
            field=models.CharField(choices=[('Annual Report', 'Annual Report'), ('Docket', 'Docket')], default='Annual Report', max_length=100, verbose_name='FileType '),
        ),
    ]
