# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0020_auto_20191111_0625'),
        ('Events', '0008_eventconfig_eventextended'),
        ('mcms', '0005_auto_20191111_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateCorporates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Corporate Name')),
                ('team', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Select Team')),
                ('no_of_teams', models.IntegerField(default=1)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event')),
                ('many_ngos', models.ManyToManyField(related_name='duplicate_corporate_csos', to='NGO.NGO')),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='donors',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='fundraisers',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='visitors',
        ),
    ]
