# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms', '0006_auto_20200319_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='donors',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='fundraisers',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='visitors',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
