# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms', '0007_auto_20200322_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.IntegerField(default=2),
        ),
    ]
