# Generated by Django 3.2 on 2021-07-15 17:43

from django.db import migrations, models
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('mcms', '0008_userprofile_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aroundtheweb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aroundtheweb',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='aroundtheweb',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Byline/ Summary'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Blog title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='youtube_embedd',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='checkcso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codescript',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Code to be inserted'),
        ),
        migrations.AlterField(
            model_name='codescript',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile1'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile2'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone1'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone2'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone3'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='summary',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='csochangeuserdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='csorequesttoparticipate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='csorequesttoparticipate',
            name='last_year_report',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='csousers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Url for album'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Image name'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='year',
            field=models.CharField(choices=[('2015', 2015), ('2016', 2016), ('2017', 2017), ('2018', 2018), ('2019', 2019), ('2020', 2020), ('2021', 2021), ('2022', 2022), ('2023', 2023), ('2024', 2024), ('2025', 2025), ('2026', 2026), ('2027', 2027), ('2028', 2028), ('2029', 2029), ('2030', 2030), ('2031', 2031), ('2032', 2032), ('2033', 2033), ('2034', 2034), ('2035', 2035), ('2036', 2036), ('2037', 2037), ('2038', 2038), ('2039', 2039), ('2040', 2040), ('2041', 2041), ('2042', 2042), ('2043', 2043), ('2044', 2044), ('2045', 2045), ('2046', 2046), ('2047', 2047), ('2048', 2048), ('2049', 2049)], max_length=20),
        ),
        migrations.AlterField(
            model_name='iccontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iccontentdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iccontentdetails',
            name='numb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='image',
            name='URL',
            field=models.URLField(blank=True, verbose_name='Link url'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caption * '),
        ),
        migrations.AlterField(
            model_name='individualactivation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Your message to the CSO'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CSO Contact Person '),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='CSO Email Id *'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='name',
            field=models.CharField(max_length=100, verbose_name='CSO Name'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CSO Contact Number '),
        ),
        migrations.AlterField(
            model_name='invite',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='CSO Website Link'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='your_email',
            field=models.EmailField(max_length=254, verbose_name='Your Email Id *'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='your_name',
            field=models.CharField(max_length=100, verbose_name='Your Name *'),
        ),
        migrations.AlterField(
            model_name='link',
            name='URL',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link url'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Byline/ Summary'),
        ),
        migrations.AlterField(
            model_name='ourevents',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ourevents',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ourevents',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='ourinitiatives',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ourinitiatives',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='banner1',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='banner2',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='banner3',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='ptype',
            field=models.CharField(blank=True, choices=[('aboutus', 'aboutus'), ('contactus', 'contactus'), ('event', 'event'), ('login', 'login'), ('thankyou', 'thankyou'), ('Food For Change', 'Food For Change'), ('Under The Stars', 'Under The Stars'), ('Seva Mela', 'Seva Mela'), ('others', 'others')], max_length=100, null=True, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='salutations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salutations',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name*'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Displaying order'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender *'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='prefix',
            field=models.CharField(choices=[('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Mis', 'Miss'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Sr', 'Sr'), ('Col', 'Colonel')], max_length=10, verbose_name='Prefix *'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen *'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='webURL',
            field=models.URLField(blank=True, max_length=60, null=True, verbose_name='Web URL'),
        ),
        migrations.AlterField(
            model_name='stafftype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stafftype',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=400, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(blank=True, choices=[('1', 'NGO'), ('2', 'Individual'), ('3', 'Fundraiser')], max_length=100, null=True, verbose_name='UserType '),
        ),
        migrations.AlterField(
            model_name='userupdatecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='DuplicateCorporates',
        ),
    ]
