# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitybib',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.Donation'),
        ),
        migrations.AlterField(
            model_name='fundraisertypedetails',
            name='ftype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.FundraiserType'),
        ),
        migrations.AlterField(
            model_name='ngoappeals',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
        migrations.AlterField(
            model_name='ngosubscription',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
        migrations.AlterField(
            model_name='participatefundraiserinevent',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
    ]
