# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_auto_20190122_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ngoappeals',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ngoappeals',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngoappeals',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ngocommunication',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ngocommunication',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngocommunication',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ngokeywords',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngokeywords',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
