# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20190122_0713'),
        ('Projects', '0001_initial'),
        ('wishtree', '0002_auto_20190122_0704'),
        ('NGO', '0003_auto_20190122_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Project'),
        ),
        migrations.AddField(
            model_name='donation',
            name='wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishtree.Wish'),
        ),
        migrations.AddField(
            model_name='donation',
            name='wishtree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishtree.WishTree'),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser_project', to='Projects.Project'),
        ),
        migrations.AddField(
            model_name='fundraiserauditlogentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_auditlog_fundraiser_project', to='Projects.Project'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='project',
            field=models.ManyToManyField(to='Projects.Project'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='we_are_on',
            field=models.ManyToManyField(to='Projects.SocialNetwork'),
        ),
        migrations.AddField(
            model_name='offlinedonation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
        migrations.AddField(
            model_name='participatefundraiserinevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ngocommunication',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
    ]
