# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20190122_0713'),
        ('NGO', '0005_auto_20190122_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatecorporates',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='register_status',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (1, b'Pending'), (2, b'Success')], default=1),
        ),
        migrations.AlterField(
            model_name='ngoauditlogentry',
            name='register_status',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (1, b'Pending'), (2, b'Success')], default=1),
        ),
    ]
