# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
#import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0006_auto_20190125_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChartWidgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                #('widgetquery', django_mysql.models.JSONField(default=dict)),
                ('chart_header', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ngo',
            name='register_status',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (1, b'Pending'), (2, b'Success'), (3, b'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='ngoauditlogentry',
            name='register_status',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (1, b'Pending'), (2, b'Success'), (3, b'Open')], default=1),
        ),
        migrations.AddField(
            model_name='dashboardchartwidgets',
            name='widgettype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.DashboardWidgetsTypes'),
        ),
    ]
