# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0007_auto_20190315_0701'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='dashboardchartwidgets',
#            name='widgetquery',
#        ),
        migrations.AddField(
            model_name='dashboardchartwidgets',
            name='widgetquery_sql',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
