# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0008_auto_20190318_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardchartwidgets',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name=b'Slug'),
        ),
    ]
