# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('NGO', '0009_dashboardchartwidgets_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReceipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=b'static/attachment/%Y/%m/%d')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopEventAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('award_type', models.CharField(blank=True, choices=[(b'CSOs', b'CSOs'), (b'Fundraiser', b'Fundraiser'), (b'Corporate', b'Corporate')], max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
