# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 12:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0011_accrossthecountry_homepagespeak'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReachOutHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('headline', models.CharField(blank=True, max_length=350, null=True)),
                ('banner', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'description')),
                ('icon', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReachOutProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=350, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=350, null=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
                ('header', models.CharField(blank=True, max_length=350, null=True)),
                ('header_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'header_description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
