# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0012_reachoutheading_reachoutprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageMediaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('mediatype', models.CharField(blank=True, choices=[(b'GIF', b'GIF'), (b'VIDEO', b'VIDEO'), (b'PHOTO', b'PHOTO')], max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.FileField(blank=True, help_text=b'Upload files in Video/Gif/Image', null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'home banner')),
                ('url', models.URLField(blank=True, help_text=b'For example : https://www.youtube.com/embed/23WbluYCUe8', null=True, verbose_name=b'Youtube Embedded Link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
