# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0013_homepagemediacontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField()),
                ('types', models.PositiveIntegerField(choices=[(0, b'Keywords'), (1, b'Categories')])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.Classification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cso_Classification_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('classification', models.ManyToManyField(blank=True, null=True, to='NGO.Classification')),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
