# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-11 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0015_auto_20190509_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagemediacontent',
            old_name='banner',
            new_name='media_banner',
        ),
        migrations.RenameField(
            model_name='homepagespeak',
            old_name='title',
            new_name='speech_title',
        ),
        migrations.RenameField(
            model_name='homepagespeak',
            old_name='video',
            new_name='speech_video',
        ),
    ]
