# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-17 12:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0016_auto_20190611_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pan_card_image',
            field=models.FileField(blank=True, help_text=b'Upload files in Pdf/Image', null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'Pan Card'),
        ),
        migrations.AlterField(
            model_name='accrossthecountry',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='accrossthecountry',
            name='video',
            field=models.URLField(verbose_name=b'Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='homepagemediacontent',
            name='media_banner',
            field=models.FileField(blank=True, help_text=b'Upload files in Video/Gif/Image', null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'Upload Banner'),
        ),
        migrations.AlterField(
            model_name='homepagemediacontent',
            name='mediatype',
            field=models.CharField(blank=True, choices=[(b'GIF', b'GIF'), (b'VIDEO', b'VIDEO'), (b'PHOTO', b'PHOTO')], max_length=100, null=True, verbose_name=b'Banner Type'),
        ),
        migrations.AlterField(
            model_name='homepagemediacontent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Banner Text'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='headline',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name=b'Main title'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='speach',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'Story'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='speech_title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name=b'Story title'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='speech_video',
            field=models.URLField(verbose_name=b'Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='our_mission',
            field=ckeditor.fields.RichTextField(help_text=b'Should not exceed 210 characters', verbose_name=b'Mission Statement*'),
        ),
        migrations.AlterField(
            model_name='ngoauditlogentry',
            name='our_mission',
            field=ckeditor.fields.RichTextField(help_text=b'Should not exceed 210 characters', verbose_name=b'Mission Statement*'),
        ),
    ]
