# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-11 06:25
from __future__ import unicode_literals

import csr.views
from django.db import migrations
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0019_sharedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrossthecountry',
            name='banner',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='fundraiserauditlogentry',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='front_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text=b'Upload Logo of size 90x120.', null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text=b'Upload logo of size less than 1Mb.', null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='ngoauditlogentry',
            name='front_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text=b'Upload Logo of size 90x120.', null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='ngoauditlogentry',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text=b'Upload logo of size less than 1Mb.', null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='reachoutheading',
            name='banner',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='reachoutheading',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='reachoutprogram',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
    ]
