# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0021_auto_20200403_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='fund_status',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='fundraiserauditlogentry',
            name='fund_status',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='ngo',
            name='ngos_status',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='ngoauditlogentry',
            name='ngos_status',
            field=models.IntegerField(default=2),
        ),
    ]
