# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-11-19 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0022_auto_20200612_1315'),
        ('NGO', '0022_auto_20200515_1824'),
    ]

    operations = [
    ]
