# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-11-19 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0023_merge_20201112_1325'),
        ('NGO', '0023_merge_20201119_2056'),
    ]

    operations = [
    ]
