# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-12-22 06:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0023_merge_20201119_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecorporates',
            name='team',
            field=models.CharField(blank=True, choices=[(b'Team-10', b'Team-10'), (b'Team-12', b'Team-12'), (b'Team-15', b'Team-15'), (b'Team-25', b'Team-25'), (b'Team-30', b'Team-30'), (b'Team-40', b'Team-40'), (b'Team-45', b'Team-45'), (b'Team-60', b'Team-60'), (b'Team-100', b'Team-100'), ('Corporate Cares Team 25', 'Corporate Cares Team 25'), ('Covid Care Fundrasier', 'Covid Care Fundrasier'), ('Care Champion Silver', 'Care Champion Silver'), ('Care Champion Gold', 'Care Champion Gold'), ('Care Champion Diamond', 'Care Champion Diamond'), ('Care Champion Platinum', 'Care Champion Platinum'), ('Millennial Champion', 'Millennial Champion'), ('Team 15 Corporate Cares', 'Team 15 Corporate Cares'), ('Team 30 Corporate Cares', 'Team 30 Corporate Cares'), ('Team 45 Corporate Cares', 'Team 45 Corporate Cares'), ('Corporate Cares  Team 40', 'Corporate Cares  Team 40'), ('iSupport', 'iSupport'), ('Covid Cares Fundraiser', 'Covid Cares Fundraiser'), ('Silver Care Champion', 'Silver Care Champion'), ('Gold Care Champion', 'Gold Care Champion'), ('Diamond Care Champion', 'Diamond Care Champion'), ('Platinum Care Champion', 'Platinum Care Champion'), ('Corporate Cares Team 15', 'Corporate Cares Team 15'), ('Corporate Cares Team 60', 'Corporate Cares Team 60'), ('Corporate Cares Team 7', 'Corporate Cares Team 7'), ('Millennial Champions', 'Millennial Champions'), ('Corporate Cares Team 40', 'Corporate Cares Team 40'), ('Corporate Cares Team 80', 'Corporate Cares Team 80'), ('Corporate Cares Team 120', 'Corporate Cares Team 120'), ('Corporate Cares Team 160', 'Corporate Cares Team 160'), ('Corporate Cares Team 220', 'Corporate Cares Team 220')], max_length=200, null=True, verbose_name=b'Select Team'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='description',
            field=ckeditor.fields.RichTextField(help_text=b'Should not exceed 2000 characters', verbose_name=b'Your Appeal to People :*'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='thank_msg',
            field=ckeditor.fields.RichTextField(blank=True, help_text=b'Should not exceed 2000 characters', null=True, verbose_name=b'Write a thank you message:(This message goes to your donors as soon as they donate) :*'),
        ),
        migrations.AlterField(
            model_name='fundraiserauditlogentry',
            name='description',
            field=ckeditor.fields.RichTextField(help_text=b'Should not exceed 2000 characters', verbose_name=b'Your Appeal to People :*'),
        ),
        migrations.AlterField(
            model_name='fundraiserauditlogentry',
            name='thank_msg',
            field=ckeditor.fields.RichTextField(blank=True, help_text=b'Should not exceed 2000 characters', null=True, verbose_name=b'Write a thank you message:(This message goes to your donors as soon as they donate) :*'),
        ),
    ]
