# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-12-22 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0024_auto_20201222_1144'),
        ('NGO', '0024_merge_20201119_2152'),
    ]

    operations = [
    ]
