# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-02-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0024_auto_20201222_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='deduction_pecentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
