# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-02-15 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0025_donation_deduction_pecentage'),
        ('NGO', '0025_merge_20201222_1206'),
    ]

    operations = [
    ]
