# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-03-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0026_merge_20210215_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecorporates',
            name='team',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Select Team'),
        ),
    ]
