# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-03-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0027_auto_20210330_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatecorporates',
            name='fundraiser_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.FundraiserType'),
        ),
    ]
