# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-04-06 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0028_duplicatecorporates_fundraiser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='card_type',
            field=models.CharField(blank=True, choices=[('PAN', b'PAN Card'), ('AC', b'Aadhar Card')], max_length=200, null=True, verbose_name=b'Card Type'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pan_card',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'PAN or Adhar Number'),
        ),
    ]
