# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-06-23 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGO', '0030_auto_20210406_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='manualrecieptnodate',
            field=models.DateField(blank=True, null=True, verbose_name=b'Mannual Recipt Creation Date'),
        ),
        migrations.AddField(
            model_name='donation',
            name='recieptno_createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
