# Generated by Django 3.2 on 2021-07-15 17:43

import ckeditor.fields
import csr.views
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('csr', '0006_auto_20210715_1743'),
        ('wishtree', '0003_wishtree_archive'),
        ('Projects', '0002_auto_20210715_1743'),
        ('mcms', '0009_auto_20210715_1743'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGO', '0032_auto_20210624_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoauditlogentry',
            name='action_user',
        ),
        migrations.RemoveField(
            model_name='ngoauditlogentry',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='ngoauditlogentry',
            name='contact_person',
        ),
        migrations.AlterField(
            model_name='accrossthecountry',
            name='banner',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='accrossthecountry',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accrossthecountry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accrossthecountry',
            name='video',
            field=models.URLField(verbose_name='Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text='Upload Logo of size 90x120.', null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Emergency Name'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Emergency Number'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='friend_number1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Friend Number1'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='friend_number2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Friend Number2'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=80, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='proof',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Upload ID Proof'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='target_hrs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Target Hours'),
        ),
        migrations.AlterField(
            model_name='charitybib',
            name='target_min',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Target Minutes'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='types',
            field=models.PositiveIntegerField(choices=[(0, 'Keywords'), (1, 'Categories')]),
        ),
        migrations.AlterField(
            model_name='cso_classification_relation',
            name='classification',
            field=models.ManyToManyField(blank=True, to='NGO.Classification'),
        ),
        migrations.AlterField(
            model_name='cso_classification_relation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cso_classification_relation',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='NGO.CsoClassificationKeyword'),
        ),
        migrations.AlterField(
            model_name='csoclassificationkeyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboardchartwidgets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboardchartwidgets',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='dashboardwidgetstypes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doantionmailer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doantionmailer',
            name='mailtype',
            field=models.CharField(blank=True, choices=[('Donation', 'Donation'), ('Registration', 'Registration'), ('AdminMails', 'AdminMails')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved On'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='card_type',
            field=models.CharField(blank=True, choices=[('PAN', 'PAN Card'), ('AC', 'Aadhar Card')], max_length=200, null=True, verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='csrproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csr.csrprojects'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='NGO_fundraiser', to='NGO.fundraiser'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='manualrecieptnodate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mannual Recipt Creation Date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NGO.ngo'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pan_card',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PAN or Adhar Number'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pan_card_image',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Pan Card'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Projects.project'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recieptno_createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='txnid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Id'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wishtree.wish'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='wishtree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wishtree.wishtree'),
        ),
        migrations.AlterField(
            model_name='donationreceipts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donationreceipts',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='static/attachment/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='duplicatecorporates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='duplicatecorporates',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Corporate Name'),
        ),
        migrations.AlterField(
            model_name='duplicatecorporates',
            name='team',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Select Team'),
        ),
        migrations.AlterField(
            model_name='foreignerdonationdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='atype',
            field=models.CharField(blank=True, choices=[('iCare', 'iCare'), ('care champion silver', 'care champion silver'), ('care champion gold', 'care champion gold'), ('Corporate care team 30', 'Corporate care team 30'), ('Corporate care team 20', 'Corporate care team 20')], max_length=200, null=True, verbose_name='Appeal Type '),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name '),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Should not exceed 2000 characters', verbose_name='Your Appeal to People :*'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='fundraiser_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NGO.fundraisertype'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='goal_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of money you hope to raise:*'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Page Title'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NGO.ngo'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Projects.project'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='thank_msg',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Should not exceed 2000 characters', null=True, verbose_name='Write a thank you message:(This message goes to your donors as soon as they donate) :*'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Fundraising Page Title(100 Character Max):*'),
        ),
        migrations.AlterField(
            model_name='fundraisertype',
            name='fund_choice',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundraisertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundraisertypedetails',
            name='download_form',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Download Form'),
        ),
        migrations.AlterField(
            model_name='fundraisertypedetails',
            name='enter_in_digits',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter in digits'),
        ),
        migrations.AlterField(
            model_name='fundraisertypedetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundraisertypedetails',
            name='minimum_pledge',
            field=models.CharField(blank=True, help_text='Display in Front End', max_length=200, null=True, verbose_name='Minimum Pledge'),
        ),
        migrations.AlterField(
            model_name='homepagemediacontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepagemediacontent',
            name='media_banner',
            field=models.FileField(blank=True, help_text='Upload files in Video/Gif/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Upload Banner'),
        ),
        migrations.AlterField(
            model_name='homepagemediacontent',
            name='mediatype',
            field=models.CharField(blank=True, choices=[('GIF', 'GIF'), ('VIDEO', 'VIDEO'), ('PHOTO', 'PHOTO')], max_length=100, null=True, verbose_name='Banner Type'),
        ),
        migrations.AlterField(
            model_name='homepagemediacontent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banner Text'),
        ),
        migrations.AlterField(
            model_name='homepagemediacontent',
            name='url',
            field=models.URLField(blank=True, help_text='For example : https://www.youtube.com/embed/23WbluYCUe8', null=True, verbose_name='Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='headline',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Main title'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='speach',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='speech_title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Story title'),
        ),
        migrations.AlterField(
            model_name='homepagespeak',
            name='speech_video',
            field=models.URLField(verbose_name='Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='need',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='need',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='a12',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='12A'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='a12_receipt',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='12A Approval'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ACRONYM'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='audited_balance_sheet',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Upload Audited Balance Sheet'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='black_board_message',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Should not exceed 190 characters', null=True, verbose_name='Black board messages'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NGO.cause', verbose_name='Primary Cause'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mcms.userprofile'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='credibility_norms',
            field=models.BooleanField(default=False, verbose_name='Do you follow the Credibility Alliance norms for transparency and Disclosure'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='established_on',
            field=models.DateField(verbose_name='Year Founded'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='fcra',
            field=models.CharField(blank=True, choices=[('NA', 'Not Applicable'), ('VA', 'Applicable')], max_length=50, null=True, verbose_name='FCRA'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='fcra_date',
            field=models.DateField(blank=True, null=True, verbose_name='FCRA Validity Till'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='fcra_receipt',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='FCRA Receipt'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='fcra_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='FCRA NO'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='front_image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text='Upload Logo of size 90x120.', null=True, upload_to='static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='fund_utilisation_statement',
            field=models.CharField(blank=True, help_text='Should not exceed 350 characters', max_length=400, null=True, verbose_name='Fund Requirement statement'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='g80_receipt',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='80G Approval'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text='Upload logo of size less than 1Mb.', null=True, upload_to='static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='latest_fin',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Latest Financials'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Page Title'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name of the CSO'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='our_mission',
            field=ckeditor.fields.RichTextField(help_text='Should not exceed 210 characters', verbose_name='Mission Statement*'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='pan_card',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Pan Card'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='primary_focus',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Focus(Primary)'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='profit_loss_statement',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Upload Profit & Loss Statement'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='reference',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='reg_no',
            field=models.CharField(max_length=40, verbose_name='Charity Registration No'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='register_status',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'Pending'), (2, 'Success'), (3, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='regn_type',
            field=models.CharField(blank=True, choices=[('Trust', 'Trust'), ('Society', 'Society'), ('Pvt Ltd Company', 'Pvt Ltd Company'), ('Section 25 Company', 'Section 25 Company'), ('Others', 'Others')], max_length=30, null=True, verbose_name='Regn Type'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='secondary_cause',
            field=models.ManyToManyField(blank=True, related_name='cso_secondarycause', to='NGO.Cause', verbose_name='Secondary Cause (Click on cause to select and unselect)'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='secondary_focus',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='size',
            field=models.CharField(choices=[('VS', 'Very Small 0-0.99 Lakh'), ('S', 'Small 0-2.99 Crore'), ('M', 'Medium 3-7.99 Crore'), ('L', 'Large 8 and above')], max_length=3, verbose_name='Turnover/Size'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='slug',
            field=models.SlugField(blank=True, help_text='For example : http://www.icfn.in/adhm/YOURTEXT/', null=True, verbose_name='Your own india cares url'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='undertakng',
            field=models.FileField(blank=True, help_text='Upload files in Pdf/Image', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Upload Undertaking'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='validity_35AC',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('VA', 'Valid')], max_length=50, verbose_name='35 AC Validity'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='validity_35AC_date',
            field=models.DateField(blank=True, null=True, verbose_name='35AC Validity Till'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='validity_80G',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('PM', 'Permanent'), ('PD', 'Pending'), ('VA', 'Valid')], max_length=50, verbose_name='80G Validity'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='validity_80G_date',
            field=models.DateField(blank=True, null=True, verbose_name='80G Validity Till'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='work_acheivement',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Should not exceed 1900 characters', null=True, verbose_name='Our Work'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='youtube_embedd',
            field=models.URLField(blank=True, help_text='For example : https://www.youtube.com/embed/23WbluYCUe8', null=True, verbose_name='Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='ngoappeals',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ngocommunication',
            name='fax',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='ngocommunication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ngocommunication',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='ngocommunication',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone1'),
        ),
        migrations.AlterField(
            model_name='ngocommunication',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone2'),
        ),
        migrations.AlterField(
            model_name='ngocommunication',
            name='phone3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone3'),
        ),
        migrations.AlterField(
            model_name='ngocommunication',
            name='web_address',
            field=models.URLField(blank=True, verbose_name='Web or Blog Address'),
        ),
        migrations.AlterField(
            model_name='ngokeywords',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ngosubscription',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved On'),
        ),
        migrations.AlterField(
            model_name='ngosubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ngosubscription',
            name='plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Essential', 'Essential'), ('Premium', 'Premium')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ngosubscription',
            name='txnid',
            field=models.CharField(max_length=100, verbose_name='Transaction Id'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='card_type',
            field=models.CharField(blank=True, choices=[('PAN', 'PAN Card'), ('AC', 'Aadhar Card')], max_length=200, null=True, verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cheque Number'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Date of Donation'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email of the Donor *'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='image_of_cheque',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Image of Cheque'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='landline_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Landline Number'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='pan_card',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pan Card / Adhar Card'),
        ),
        migrations.AlterField(
            model_name='offlinedonation',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque/DD', 'Cheque/DD'), ('Bank transfer', 'Bank transfer'), ('NGO Website', 'CSO Website')], max_length=200, null=True, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='otherdonation',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='otherdonation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participatefundraiserinevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reachoutheading',
            name='banner',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='reachoutheading',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='reachoutheading',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='reachoutheading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reachoutprogram',
            name='header_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header_description'),
        ),
        migrations.AlterField(
            model_name='reachoutprogram',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reachoutprogram',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='sharedetails',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Should not exceed 210 characters', verbose_name='Mission Statement*'),
        ),
        migrations.AlterField(
            model_name='sharedetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sharedetails',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Name of the CSO'),
        ),
        migrations.AlterField(
            model_name='topeventawards',
            name='award_type',
            field=models.CharField(blank=True, choices=[('CSOs', 'CSOs'), ('Fundraiser', 'Fundraiser'), ('Corporate', 'Corporate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topeventawards',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topeventawards',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='volunteerrequirements',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='volunteerrequirements',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='phone_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel No'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill'),
        ),
        migrations.DeleteModel(
            name='FundraiserAuditLogEntry',
        ),
        migrations.DeleteModel(
            name='NGOAuditLogEntry',
        ),
    ]
