# Generated by Django 3.2.8 on 2021-11-03 11:24

import csr.views
from django.db import migrations
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0033_auto_20210715_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
    ]
