# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmhistory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paytmhistory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paytmhistory',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
