# Generated by Django 3.2 on 2021-07-15 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0002_auto_20190122_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='BANKNAME',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BANK NAME'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BANK TXN ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='CURRENCY',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CURRENCY'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='GATEWAYNAME',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='GATEWAY NAME'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='ORDERID',
            field=models.CharField(max_length=300, verbose_name='ORDER ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='PAYMENTMODE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAYMENT MODE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='RESPCODE',
            field=models.IntegerField(verbose_name='RESP CODE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='RESPMSG',
            field=models.TextField(max_length=250, verbose_name='RESP MSG'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='STATUS',
            field=models.CharField(max_length=12, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNAMOUNT',
            field=models.FloatField(verbose_name='TXN AMOUNT'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNDATE',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=100, verbose_name='TXN ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
