# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 05:36
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mcms.thumbs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO', '0001_initial'),
        ('Events', '0001_initial'),
        ('mcms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpledgeDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'First Name *')),
                ('last_name', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Last Name *')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Email *')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Mobile *')),
                ('address1', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Address *')),
                ('address2', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_in_date', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'I will Deliver on')),
                ('is_fullfilled', models.BooleanField(default=False)),
                ('amount', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Amount *')),
                ('quantity', models.IntegerField(default=0, verbose_name=b'Quantity *')),
            ],
            options={
                'db_table': 'wishtree_ipledge_donation',
            },
        ),
        migrations.CreateModel(
            name='NonCashDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('required', models.CharField(max_length=200, verbose_name=b'Actual Requirement*')),
                ('completed', models.CharField(max_length=200, verbose_name=b'Completed Requirement*')),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'wishtree_non_cash_donations',
            },
        ),
        migrations.CreateModel(
            name='OtherDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=500, null=True)),
                ('address2', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity_of_gift', models.CharField(blank=True, max_length=50, null=True)),
                ('time_required', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'wishtree_other_donations',
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Wish Title *')),
                ('benefit_name', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Beneficiary Name')),
                ('slug', models.SlugField(max_length=500)),
                ('requirement', ckeditor.fields.RichTextField(verbose_name=b'Requirement *')),
                ('quantity', models.IntegerField(default=0, verbose_name=b'Quantity *')),
                ('cost_per_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Cost per Unit *')),
                ('target', models.CharField(max_length=200, verbose_name=b'Target Amount/No of Hrs *')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name=b'Start DateTime *')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name=b'End DateTime *')),
                ('place_to_deliver', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'Address to deliver *')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'City')),
                ('unit', models.CharField(blank=True, choices=[('days', b'days'), ('kgs', b'kgs'), ('hours', b'hours'), ('months', b'months'), ('units', b'units')], max_length=200, null=True, verbose_name=b'Type')),
                ('object_id', models.PositiveIntegerField()),
                ('image', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('finished', models.BooleanField(default=False)),
                ('cause', models.ManyToManyField(blank=True, null=True, to='NGO.Cause')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishtree.Wish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, help_text=b'.icfn.in', max_length=500, null=True, verbose_name=b'Make Your own Link *')),
                ('wtype', models.CharField(choices=[(b'Event', b'Event'), (b'Others', b'Others')], max_length=200, verbose_name=b'Tree Type')),
                ('code', models.CharField(max_length=50, verbose_name=b'Make Your URL*')),
                ('slug', models.SlugField(max_length=500)),
                ('image', mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'Description')),
                ('no_of_wish', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Number of Wishes*')),
                ('is_main_page', models.BooleanField(default=False)),
                ('home_page_wishes', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Home page wish count')),
                ('cause', models.ManyToManyField(blank=True, null=True, to='NGO.Cause')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Event')),
            ],
            options={
                'db_table': 'wishtree_wish_tree',
            },
        ),
        migrations.CreateModel(
            name='WishtreeCampaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name=b'Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=b'End Date')),
                ('wishtree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishtree.WishTree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishtreeCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'City name *')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcms.State')),
            ],
            options={
                'db_table': 'wishtree_wishtree_city',
            },
        ),
        migrations.CreateModel(
            name='WishtreeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('home_image', models.FileField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'Home Background')),
                ('inner_logo', models.FileField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'Logo')),
                ('tree_image', models.FileField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'Login Image')),
                ('cso_image', models.FileField(blank=True, null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'CSO page Background')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name=b'Start DateTime')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name=b'End DateTime')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishtreeNgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=500, verbose_name=b'Contact Person*')),
                ('reg_no', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Ngo Registration No*')),
                ('validity_80G', models.CharField(blank=True, choices=[('NA', b'Not Applicable'), ('PM', b'Permanent'), ('PD', b'Pending'), ('VA', b'Valid')], max_length=50, null=True, verbose_name=b'80G Validity')),
                ('validity_80G_date', models.DateField(blank=True, null=True, verbose_name=b'80G Validity Till')),
                ('validity_35AC', models.CharField(blank=True, choices=[('NA', b'Not Applicable'), ('VA', b'Valid')], max_length=50, null=True, verbose_name=b'35 AC Validity')),
                ('validity_35AC_date', models.DateField(blank=True, null=True, verbose_name=b'35AC Validity Till')),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'Summary')),
                ('logo', mcms.thumbs.ImageWithThumbsField(blank=True, help_text=b'Upload Logo of size 90x120.', null=True, upload_to=b'static/v2/%Y/%m/%d')),
                ('website', models.URLField(blank=True, null=True, verbose_name=b'Website')),
                ('pan_card', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Pan Card Number')),
                ('utype', models.CharField(blank=True, choices=[('Ngo', b'CSO'), ('Corporate', b'Corporate'), ('Group', b'Group')], max_length=50, null=True, verbose_name=b'User Type')),
                ('focus_statement', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Focus Statement')),
                ('a12', models.CharField(choices=[('NA', b'Not Applicable'), ('PM', b'Permanent'), ('PD', b'Pending'), ('VA', b'Valid')], max_length=500, verbose_name=b'12A')),
                ('a12_pdf', models.FileField(blank=True, help_text=b'Upload files in Pdf', null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'Upload A12 Receipt *')),
                ('G80_pdf', models.FileField(blank=True, help_text=b'Upload files in Pdf', null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'Upload 80G Reciept *')),
                ('pan_card_pdf', models.FileField(blank=True, help_text=b'Upload files in Pdf', null=True, upload_to=b'static/v2/%Y/%m/%d', verbose_name=b'Upload Pan Card Reciept *')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishtree.WishtreeCity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishtree_wishtree_ngo',
            },
        ),
        migrations.CreateModel(
            name='WishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('need_type', models.CharField(choices=[(b'Cash', b'Cash'), (b'Non-Cash', b'Non-Cash')], max_length=200, verbose_name=b'Need Type')),
                ('name', models.CharField(max_length=200, verbose_name=b'Wish Type')),
            ],
            options={
                'db_table': 'wishtree_wish_type',
            },
        ),
        migrations.AddField(
            model_name='wish',
            name='wishtree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishtree.WishTree'),
        ),
        migrations.AddField(
            model_name='wish',
            name='wishtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishtree.WishType', verbose_name='Wish Type *'),
        ),
        migrations.AddField(
            model_name='otherdonations',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishtree.Wish'),
        ),
        migrations.AddField(
            model_name='otherdonations',
            name='wishtree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishtree.WishTree'),
        ),
        migrations.AddField(
            model_name='noncashdonations',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishtree.Wish'),
        ),
        migrations.AddField(
            model_name='ipledgedonation',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishtree.Wish'),
        ),
        migrations.AddField(
            model_name='ipledgedonation',
            name='wishtree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishtree.WishTree'),
        ),
    ]
