# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishtree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wishtree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishtree.WishTree'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
