# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-03-29 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishtree', '0002_auto_20190122_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishtree',
            name='archive',
            field=models.PositiveIntegerField(blank=True, choices=[(0, b'No'), (1, b'Yes')], default=0, null=True),
        ),
    ]
