# Generated by Django 3.2 on 2021-07-15 17:43

import ckeditor.fields
from django.db import migrations, models
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0033_auto_20210715_1743'),
        ('wishtree', '0003_wishtree_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipledgedonation',
            name='address1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address *'),
        ),
        migrations.AlterField(
            model_name='ipledgedonation',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Amount *'),
        ),
        migrations.AlterField(
            model_name='ipledgedonation',
            name='delivery_in_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='I will Deliver on'),
        ),
        migrations.AlterField(
            model_name='ipledgedonation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email *'),
        ),
        migrations.AlterField(
            model_name='ipledgedonation',
            name='first_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='First Name *'),
        ),
        migrations.AlterField(
            model_name='ipledgedonation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipledgedonation',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Last Name *'),
        ),
        migrations.AlterField(
            model_name='ipledgedonation',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile *'),
        ),
        migrations.AlterField(
            model_name='ipledgedonation',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity *'),
        ),
        migrations.AlterField(
            model_name='noncashdonations',
            name='completed',
            field=models.CharField(max_length=200, verbose_name='Completed Requirement*'),
        ),
        migrations.AlterField(
            model_name='noncashdonations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noncashdonations',
            name='required',
            field=models.CharField(max_length=200, verbose_name='Actual Requirement*'),
        ),
        migrations.AlterField(
            model_name='otherdonations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='benefit_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Beneficiary Name'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='cause',
            field=models.ManyToManyField(blank=True, to='NGO.Cause'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='cost_per_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cost per Unit *'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End DateTime *'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Wish Title *'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='place_to_deliver',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Address to deliver *'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity *'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='requirement',
            field=ckeditor.fields.RichTextField(verbose_name='Requirement *'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start DateTime *'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='target',
            field=models.CharField(max_length=200, verbose_name='Target Amount/No of Hrs *'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='unit',
            field=models.CharField(blank=True, choices=[('days', 'days'), ('kgs', 'kgs'), ('hours', 'hours'), ('months', 'months'), ('units', 'units')], max_length=200, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='archive',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='cause',
            field=models.ManyToManyField(blank=True, to='NGO.Cause'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Make Your URL*'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='home_page_wishes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Home page wish count'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='image',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='name',
            field=models.CharField(blank=True, help_text='.icfn.in', max_length=500, null=True, verbose_name='Make Your own Link *'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='no_of_wish',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Number of Wishes*'),
        ),
        migrations.AlterField(
            model_name='wishtree',
            name='wtype',
            field=models.CharField(choices=[('Event', 'Event'), ('Others', 'Others')], max_length=200, verbose_name='Tree Type'),
        ),
        migrations.AlterField(
            model_name='wishtreecampaigns',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='wishtreecampaigns',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishtreecampaigns',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='wishtreecity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishtreecity',
            name='name',
            field=models.CharField(max_length=200, verbose_name='City name *'),
        ),
        migrations.AlterField(
            model_name='wishtreeimage',
            name='cso_image',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='CSO page Background'),
        ),
        migrations.AlterField(
            model_name='wishtreeimage',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End DateTime'),
        ),
        migrations.AlterField(
            model_name='wishtreeimage',
            name='home_image',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Home Background'),
        ),
        migrations.AlterField(
            model_name='wishtreeimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishtreeimage',
            name='inner_logo',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='wishtreeimage',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start DateTime'),
        ),
        migrations.AlterField(
            model_name='wishtreeimage',
            name='tree_image',
            field=models.FileField(blank=True, null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Login Image'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='G80_pdf',
            field=models.FileField(blank=True, help_text='Upload files in Pdf', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Upload 80G Reciept *'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='a12',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('PM', 'Permanent'), ('PD', 'Pending'), ('VA', 'Valid')], max_length=500, verbose_name='12A'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='a12_pdf',
            field=models.FileField(blank=True, help_text='Upload files in Pdf', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Upload A12 Receipt *'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='contact_person',
            field=models.CharField(max_length=500, verbose_name='Contact Person*'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='focus_statement',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Focus Statement'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='logo',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text='Upload Logo of size 90x120.', null=True, upload_to='static/v2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='pan_card',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pan Card Number'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='pan_card_pdf',
            field=models.FileField(blank=True, help_text='Upload files in Pdf', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Upload Pan Card Reciept *'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='reg_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ngo Registration No*'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='utype',
            field=models.CharField(blank=True, choices=[('Ngo', 'CSO'), ('Corporate', 'Corporate'), ('Group', 'Group')], max_length=50, null=True, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='validity_35AC',
            field=models.CharField(blank=True, choices=[('NA', 'Not Applicable'), ('VA', 'Valid')], max_length=50, null=True, verbose_name='35 AC Validity'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='validity_35AC_date',
            field=models.DateField(blank=True, null=True, verbose_name='35AC Validity Till'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='validity_80G',
            field=models.CharField(blank=True, choices=[('NA', 'Not Applicable'), ('PM', 'Permanent'), ('PD', 'Pending'), ('VA', 'Valid')], max_length=50, null=True, verbose_name='80G Validity'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='validity_80G_date',
            field=models.DateField(blank=True, null=True, verbose_name='80G Validity Till'),
        ),
        migrations.AlterField(
            model_name='wishtreengo',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='wishtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishtype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Wish Type'),
        ),
        migrations.AlterField(
            model_name='wishtype',
            name='need_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Non-Cash', 'Non-Cash')], max_length=200, verbose_name='Need Type'),
        ),
    ]
