# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
        ('NGO', '0003_auto_20190122_0655'),
        ('Events', '0002_auto_20190122_0640'),
        ('csr', '0003_auto_20190122_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='csr',
            name='events',
            field=models.ManyToManyField(related_name='CSR_events', to='Events.Event'),
        ),
        migrations.AddField(
            model_name='csr',
            name='project',
            field=models.ManyToManyField(to='Projects.Project'),
        ),
        migrations.AddField(
            model_name='csrprojects',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.Cause'),
        ),
        migrations.AddField(
            model_name='csrprojects',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcms.UserProfile'),
        ),
        migrations.AlterField(
            model_name='csrusers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
