# Generated by Django 3.2 on 2021-07-15 17:43

import ckeditor.fields
import csr.views
from django.db import migrations, models
import mcms.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('csr', '0005_auto_20191111_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csr',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ACRONYM'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='black_board_message',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Black board messages'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='established_on',
            field=models.DateField(verbose_name='Year Founded*'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='fcra',
            field=models.CharField(blank=True, choices=[('NA', 'Not Applicable'), ('VA', 'Applicable')], max_length=50, null=True, verbose_name='FCRA NO *'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='fcra_date',
            field=models.DateField(blank=True, null=True, verbose_name='FCRA Validity Till'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='fcra_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='FCRA NO.'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='fund_utilisation_statement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fund Utilisation statement'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='icon',
            field=mcms.thumbs.ImageWithThumbsField(blank=True, help_text='Upload Logo of size 90x120.', null=True, upload_to='static/v2/%Y/%m/%d', validators=[csr.views.validate_image]),
        ),
        migrations.AlterField(
            model_name='csr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='latest_fin',
            field=models.FileField(blank=True, help_text='Upload files in Pdf', null=True, upload_to='static/v2/%Y/%m/%d', verbose_name='Latest Financials'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name of the CSR*'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='our_mission',
            field=ckeditor.fields.RichTextField(verbose_name='Mission Statement*'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='reference',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='reg_no',
            field=models.CharField(max_length=40, verbose_name='Charity Registration No*'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='regn_type',
            field=models.CharField(choices=[('Trust', 'Trust'), ('Society', 'Society'), ('Pvt Ltd Company', 'Pvt Ltd Company'), ('Section 25 Company', 'Section 25 Company'), ('Others', 'Others')], max_length=30, verbose_name='Regn Type*'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='size',
            field=models.CharField(choices=[('VS', 'Very Small 0-0.99 Lakh'), ('S', 'Small 0-2.99 Crore'), ('M', 'Medium 3-7.99 Crore'), ('L', 'Large 8 and above')], max_length=3, verbose_name='Turnover/Size*'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='validity_35AC',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('VA', 'Valid')], max_length=50, verbose_name='35 AC Validity'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='validity_35AC_date',
            field=models.DateField(blank=True, null=True, verbose_name='35AC Validity Till'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='validity_80G',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('PM', 'Permanent'), ('PD', 'Pending'), ('VA', 'Valid')], max_length=50, verbose_name='80G Validity'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='validity_80G_date',
            field=models.DateField(blank=True, null=True, verbose_name='80G Validity Till'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='web_address',
            field=models.URLField(blank=True, verbose_name='Web or Blog Address'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='work_acheivement',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Work Achievements'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='youtube_embedd',
            field=models.URLField(blank=True, verbose_name='Youtube Embedded Link'),
        ),
        migrations.AlterField(
            model_name='csrcommunication',
            name='fax',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='csrcommunication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='csrcommunication',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='csrcommunication',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone1'),
        ),
        migrations.AlterField(
            model_name='csrcommunication',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone2'),
        ),
        migrations.AlterField(
            model_name='csrcommunication',
            name='phone3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone3'),
        ),
        migrations.AlterField(
            model_name='csrcommunication',
            name='web_address',
            field=models.URLField(blank=True, verbose_name='Web or Blog Address'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='amount_in_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Budget in digits'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='contact_person',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact Peron'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='duration',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Project Name *'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='no_to_be_impacted',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Numbers to be impacted'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title *'),
        ),
        migrations.AlterField(
            model_name='csrprojects',
            name='total_budget',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Total Budget'),
        ),
        migrations.AlterField(
            model_name='csrusers',
            name='cname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='csrusers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='csrusers',
            name='phoneno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile Number'),
        ),
    ]
